// import PACKAGE from '../package.json'

// const DEPS = PACKAGE.dependencies

// Object.keys(DEPS).forEach(k => {
//   require(`../node_modules/${k}`)
// })
import '@things-scene/baidu-map'
import '@things-scene/chartjs'
import '@things-scene/clock'
import '@things-scene/clone'
import '@things-scene/compass'
import '@things-scene/data-transform'
import '@things-scene/echart'
import '@things-scene/excel'
import '@things-scene/firebase'
import '@things-scene/forklift'
import '@things-scene/form'
import '@things-scene/gauge'
import '@things-scene/google-map'
import '@things-scene/half-roundrect'
import '@things-scene/indoor-map'
import '@things-scene/legend'
import '@things-scene/marker'
import '@things-scene/mqtt'
import '@things-scene/news-ticker'
import '@things-scene/person'
import '@things-scene/progressbar'
import '@things-scene/random'
import '@things-scene/restful'
import '@things-scene/slam'
import '@things-scene/stomp'
import '@things-scene/tab'
import '@things-scene/table'
import '@things-scene/traffic'
import '@things-scene/visualizer'
import '@things-scene/wheel-sorter'
